
    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;
